### ISSUE TITLE
I18n / internationalization

### ISSUE THREAD

**Issue by sblum51** [sblum51/Run-Run-Run#6]
We are French and some terms of the views are in french.I wish to propose the app in english. 2 possibilities : RunRunRun will be only in english or provide 1 app and users will have the choice between two (or more) languages.

**Comment by fabi1cazenave** [comment]
https://github.com/fabi1cazenave/webL10n is there for you

**Comment by sblum51** [comment]
thanks for this feedback

**Comment by sblum51** [comment]
webL10n is now installed. I just need contributors for the translations :)
